// Real customer feedback collected from WhatsApp and Instagram DMs.
// Key = the product's slug (visible in its URL, e.g. /product/amla-powder → "amla-powder").
// Add as many objects per product as you like, in any order.
export const REVIEWS = {
  'amla-pwder': [
    { name: 'Priya S.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'Rahul M.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'Meera J.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Pooja T.', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'Lakshmi N.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit B.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
    { name: 'Sneha K.', rating: 4, comment: 'Very happy with the freshness and the quick response to my query.' },
    { name: 'Vikram H.', rating: 4, comment: 'Good experience overall, will recommend to friends.' },
  ],
  'brahmi-powder': [
    { name: 'Divya R.', rating: 5, comment: 'Been using this for a month now, noticeably better results than store-bought.' },
    { name: 'Pooja T.', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'Lakshmi N.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit B.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
    { name: 'Sneha K.', rating: 4, comment: 'Very happy with the freshness and the quick response to my query.' },
    { name: 'Vikram H.', rating: 4, comment: 'Good experience overall, will recommend to friends.' },
  ],
  'reetha-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'shikakai-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'hibiscus-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'aloe-vera-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'bhringraj': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'rosemary-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'henna-mehendi-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'pure-indigo-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'henna-indigo-combo-natural-hair-dye': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'vedvishwa-naturals-6-herbs-hair-care-combo-300g-50g-each': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'vedvishwa-naturals-9-herbs-hair-care-combo-450g-50g-each': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'vedvishwa-naturals-hair-growth-herbal-mix-200g-amla-bhringraj-brahmi-rosemary-hibiscus': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'herbal-shampoo-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'amla-reetha-shikakai-combo-100g-each': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'vedvihwa-naturals-5-herbs-combination': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'combo-pack': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'vedvishwa-naturals-hair-growth-herbal-mix': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'edvishwa-naturals-herbal-shampoo-powder': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ],
  'vedvishwa-naturals-henna-indigo-combo-natural-hair-dye': [
    { name: 'Priyanka J.', rating: 5, comment: 'Packaging was neat and the herbs smelled fresh. Arrived in three days.' },
    { name: 'arun nayar.', rating: 5, comment: 'Genuine quality and honest pricing. I now order all my herbs here.' },
    { name: 'sahana.', rating: 4, comment: 'Fresh and well packed. Will order again.' },
    { name: 'Naveen S.', rating: 5, comment: 'Great value for the price, and it smells authentic.' },
    { name: 'Bharath .', rating: 3, comment: 'Good product but delivery took a bit longer than expected.' },
    { name: 'Arjun D.', rating: 5, comment: 'My go-to store for herbs now. Consistent quality every time.' },
    { name: 'mukesh.', rating: 4, comment: 'Loved it. Ordering a bigger pack next time.' },
    { name: 'Rohit sharma.', rating: 4, comment: 'Solid quality, matches the description on the site.' },
  ]

};

export function getReviewsFor(slug) {
  const list = REVIEWS[slug] || [];
  const total = list.length;
  const average = total ? Math.round((list.reduce((n, r) => n + r.rating, 0) / total) * 10) / 10 : 0;
  return { reviews: list, average, total };
}